name: container-ci

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  native:
    uses: ./.github/workflows/native-artifacts.yml

  container:
    needs: native
    uses: ./.github/workflows/container-validate.yml
